### ISSUE TITLE
duplicate channel entities 

### ISSUE THREAD

**Issue by jeremykeen** [gordlea/fireboard2mqtt#2]
I have duplicate channel entities being created. I am not exactly sure what triggers a new channel but perhaps every time I connect for a new cook.
![Screen Shot 2022-11-11 at 3 45 12 PM](https://user-images.githubusercontent.com/10226529/201428275-d74cdcc2-93d2-4096-9a6e-5a7e019fba94.png)

**Comment by gordlea** [comment]
I will take a look when I get some time, thanks for reporting the bug.
