### ISSUE TITLE
fireboard Pro error 

### ISSUE THREAD

**Issue by buffalowolff** [gordlea/fireboard2mqtt#35]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[11:05:24] INFO: mqtt://core-mosquitto:1883
[11:05:25] INFO: Starting fireboard2mqtt
[11:05:25] INFO: drive enabled: true
 DEBUG fireboard2mqtt > config loaded successfully
 DEBUG fireboard2mqtt::fireboard_watcher > client authenticated successfully
 INFO  fireboard2mqtt::fireboard_watcher > checking fireboard api for updates
 ERROR fireboard2mqtt::fireboard_api     > Error parsings devices: error decoding response body: invalid type: map, expected unit at line 1 column 1620
 ERROR fireboard2mqtt::fireboard_watcher > Error fetching devices: error decoding response body: invalid type: map, expected unit at line 1 column 1620

Caused by:
    invalid type: map, expected unit at line 1 column 1620
 INFO  fireboard2mqtt                    > Current physical memory usage: 30.1 MB
 DEBUG fireboard2mqtt                    > there are 0 devices online
 DEBUG fireboard2mqtt                    > updating from fireboard cloud api in 60 seconds

**Comment by gordlea** [comment]
I am going away for a few days, but when I get back I may need your help to debug this one since I don't have a fireboard pro.

**Comment by buffalowolff** [comment]
Sounds good, and thanks

**Comment by gordlea** [comment]
Fixed by #31
