### ISSUE TITLE
add standalone docker image

### ISSUE THREAD

**Issue by scottshanafelt** [gordlea/fireboard2mqtt#36]
Hi, first let me say thank you for putting this together and sharing it!  I noticed there is a Dockerfile in the fireboard2mqtt repo, but I can't find a docker image online anywhere.

**Comment by gordlea** [comment]
The docker image is specifically for running it as a home-assistant addon, you can find it here: 
https://hub.docker.com/repository/docker/gordlea/homeassistant-addon-amd64-fireboard2mqtt/general
https://hub.docker.com/repository/docker/gordlea/homeassistant-addon-aarch64-fireboard2mqtt/general

It is built in this repo: https://github.com/gordlea/home-assistant-addons/tree/beta/fireboard2mqtt

If there is interest in a more general purpose dockerfile it could be arranged 😄

**Comment by scottshanafelt** [comment]
Great thank you, I'll give it a shot.  I personally am just trying to get it into HA and I run HA OS, so this should work.  I'd imagine anyone running HA Core only might be interested in a standalone container.

Thanks again!

**Comment by scottshanafelt** [comment]
You're the man!
