### ISSUE TITLE
Erroneous JSON: Warnings

### ISSUE THREAD

**Issue by mattdevo1** [gordlea/fireboard2mqtt#51]
In my HA Core log file, I'm seeing a bunch of these non-descriptive MQTT warnings:

```
Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:557
integration: MQTT (documentation, issues)
First occurred: 9:06:29 AM (12 occurrences)
Last logged: 9:13:32 AM

Erroneous JSON:
```

After a bit of troubleshooting, I think it's the fireboard2mqtt add-on causing this.

I turned debug logging on for the MQTT integration and here are the logs leading up to the warning:

```
2024-05-05 09:10:11.309 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on fireboard2mqtt/GJKK6737J/drive/state (qos=0): b''
2024-05-05 09:10:11.309 DEBUG (MainThread) [homeassistant.components.mqtt.sensor] Ignore empty state from 'fireboard2mqtt/GJKK6737J/drive/state'
2024-05-05 09:10:11.309 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on fireboard2mqtt/GJKK6737J/drive/attributes (qos=0): b''
2024-05-05 09:10:11.309 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Erroneous JSON: 
```

@gordlea are you seeing this issue elsewhere? Any thoughts on how I can further troubleshoot/fix? 

Thanks in advance!

**Comment by mattdevo1** [comment]
Any thoughts @gordlea ?

I'm getting thousands of them...Are you seeing any?

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:557
integration: MQTT (documentation, issues)
First occurred: May 13, 2024 at 10:12:02 AM (7005 occurrences)
Last logged: 7:36:22 PM

Erroneous JSON:

**Comment by gordlea** [comment]
Sorry, I have been on other things, I will take a look this weekend.

**Comment by mattdevo1** [comment]
> Sorry, I have been on other things, I will take a look this weekend.

No worries! I'm fairly sure this add-on is causing the issue (if I disable it, the warnings stop). But the logs are not super descriptive and I'm not sure if there is something specific in my config that might be causing it. 

Happy to help troubleshoot further if you have any idea. Thanks!

**Comment by gordlea** [comment]
Do you happen to have a drive hooked up?

**Comment by mattdevo1** [comment]
> Do you happen to have a drive hooked up?

I have a drive, but it isn't hooked up as we speak (the Fireboard is turned on/plugged into power, but I'm not currently BBQing, so the drive isn't plugged in). 

I have one that I can test with if helpful though.

**Comment by gordlea** [comment]
I'm seeing the Erroneous JSON when i start the addon with the fireboard off. I wish it gave some indication of what the bad json was. Maybe it's sending a blank string?

This might take a little while to debug, but I will look into it 😄

**Comment by mattdevo1** [comment]
> I'm seeing the Erroneous JSON when i start the addon with the fireboard off. I wish it gave some indication of what the bad json was. Maybe it's sending a blank string?
> 
> 
> 
> This might take a little while to debug, but I will look into it 😄  

Well, I'm glad I'm not the only one 😀 

I'm happy to help you test, just let me know. 

And thanks in advance!
