### ISSUE TITLE
home assistant image build has changed, 1.1.1 not working

### ISSUE THREAD

**Issue by gordlea** [gordlea/fireboard2mqtt#8]
Something in the way home assistant addon images are built has changed.

fireboard2mqtt is working locally, but fails to run when imported as a home assistant addon.

I've rolled 1.0.0 back to current in the addon repository (https://github.com/gordlea/home-assistant-addons).

**Comment by gordlea** [comment]
Sorry everyone, I'm having a lot of trouble trying to build the new images for this release. I've been working on it, but I haven't had time to really dig into this. I will do my best to resolve this next week.

**Comment by alexownsall** [comment]
> Sorry everyone, I'm having a lot of trouble trying to build the new images for this release. I've been working on it, but I haven't had time to really dig into this. I will do my best to resolve this next week.

Thanks! Appreciate it!

**Comment by fdelacou** [comment]
Any update or should we consider this integration dead? Thank you

**Comment by gordlea** [comment]
not dead, i will look tomorrow

**Comment by gordlea** [comment]
Just FYI i'm rewriting this addon using rust, should be a week or 2 before it's ready.

**Comment by fdelacou** [comment]
> Just FYI i'm rewriting this addon using rust, should be a week or 2 before it's ready.

Looking forward to it and if you need some testing, I would gladly oblige.

**Comment by mattdevo1** [comment]
I'm happy to help test too, if helpful. Thanks for your work!

**Comment by mattdevo1** [comment]
> Just FYI i'm rewriting this addon using rust, should be a week or 2 before it's ready.

How are things coming along? Anything you would like us to test over this weekend/coming week? I have a few turkeys to roast and plenty of time on my hands at the moment :)

**Comment by mattdevo1** [comment]
Hey @gordlea how is this coming along? Would love to get your Fireboard integration back up and running. Thanks in advance, and let me know if I can help test anything.

**Comment by buffalowolff** [comment]
Same concern here, hopefully this add-on hasn't gone the way of 99% of the projects I start (understandable if it has).

**Comment by gordlea** [comment]
> Same concern here, hopefully this add-on hasn't gone the way of 99% of the projects I start (understandable if it has). 

I'm happy to report a new rewritten version is about 80% complete. 

I have figured out a reliable way to load the drive data, which is nice. 

I've got the core part complete, just need to set up the MQTT discovery, then figure out the socket build part. I'll post here when I have another update.

**Comment by buffalowolff** [comment]
Awesome to hear.  For now I wrote a rest sensor for the fireboard and spark with the auth token hard coded.  It works fine but its a goofy way to do it and isn't dynamic at all.

**Comment by mattdevo1** [comment]
> > Same concern here, hopefully this add-on hasn't gone the way of 99% of the projects I start (understandable if it has). 
> 
> I'm happy to report a new rewritten version is about 80% complete. 
> 
> I have figured out a reliable way to load the drive data, which is nice. 
> 
> I've got the core part complete, just need to set up the MQTT discovery, then figure out the socket build part. I'll post here when I have another update.
> 

Great news, thank you!! Just in time for spring BBQ :) 

Let us know if you need any help testing.

**Comment by gordlea** [comment]
I could use some help testing 😄 

Take a look at #31 for instruction how

**Comment by alexownsall** [comment]
Got it installed and set up. It is working off the jump, so that is good.
Will update when I use the unit and see how it updates.

**Comment by buffalowolff** [comment]
I installed it and took a quick look and something isn't quite right (I have the pro though with the 3 thermistor probes not the 6 probes).  When I have more time maybe this weekend I'll take a more in depth look

**Comment by mattdevo1** [comment]
> I could use some help testing 😄 
> 
> 
> 
> Take a look at #31 for instruction how

I installed the beta and it started up fine. But I think your details might be hard coded in there or something? I added my Fireboard credentials, but the serial number of the device that shows up via MQTT is NOT mine (the one that shows up has a serial ending in D2 if that's helpful at all).

**Comment by mattdevo1** [comment]
> I could use some help testing 😄
> 
> Take a look at #31 for instruction how

I just sent you an email, please check it asap...

**Comment by gordlea** [comment]
> > I could use some help testing 😄
> > Take a look at #31 for instruction how
> 
> I just sent you an email, please check it asap...

Thanks so much for the discrete notifcation @mattdevo1 , changed my password immediately. Dumbass move by me to leave the credentials in there, I will scrub the repo with bfg repo-cleaner also.
